name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '10.13.0'  # Especifica la versión 10.13.0 aquí

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
